services:
  - type: web
    name: acespins-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    buildpacks:
      - key: https://github.com/render-inc/render-buildpack-chrome
      - key: python
